name: Caster
main: mcunderground\caster\Main
author: MCUnderground
version: 1.1.0
api: 1.0.0
commands: 
 cast:
  description: "Broadcasts message you input."
  permission: caster.cast
permissions:
 caster:
  default: op
  children:
   caster.cast:
    default: op
    description: Allows you to broadcast your message.
